### ISSUE TITLE
Regarding dashboard 

### ISSUE THREAD

**Issue by abhirafuru11** [spacialdb/fcm#10]
Hi Kashif,
I have a need to show the notification history send from the specific FCM key with their state : delivered successfully or missed. Thats-why i am looking for a dashboard . Because we have only got the status by server that the particular notification have reached (to particular server ie: fcm and apn,s) but cant have such information that is that particular notification is delivered to device or not?

So please help if you can do any needful.
Quick response is awaited.
Thanks

**Comment by abhirafuru11** [comment]
Hi Kashif,
It seems you dont have got time to view this once. Please have a look  and let me know if any option find regarding dashboard. It,s a little bit urgency.

Thanks:
Abhishek Kumar

**Comment by kashif** [comment]
@abhirafuru11 what do you mean by a dashboard? Is that some type of web interface to the notifications?

**Comment by abhirafuru11** [comment]
Hey Kashif, 
Hope you are doing well and thanks for your  reply. Actually i am facing a problem regarding notification delivery. Sometimes i have got success in callback of notification but  the notification is either not getting delivered or  delivered by late. This is mostly happens for Android devices in ration of approx 5-8 failure in respect of 100. This is causing a big problem because of application is real time(Taxi app like UBER). And as we are not storing success and failure of notification in to our database so we didn't getting  the actual idea that why this is happening. Thats why i am asking for a web dashboard where i am check is notification not delivered from our side or some FCM problem occurs. Can you please help me by elaborating it in some details that what  process is working between  when our server sends a push to fcm and delivery of this to app. And please let me know about any solution , because this is really to serious. :(

Quick response is awaited.

Thanks

**Comment by kashif** [comment]
ok i see so it seems some messages are not getting delivered, while others are. What this library does is make web requests to the firebase cloud service which is the one that is send the notifications.

When you send a notification via this gem, you get a response and if at the moment you are not storing that in the db, what you could try is to at least perhaps output it in some log file.

This way you can see the message from the firebase side to see if the problem is with them?

One reason a message could fail might be because of Doze restrictions, so perhaps you can try to set the `priority` of the notifications, see here: 

https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message

hope this gives you some ideas?

**Comment by abhirafuru11** [comment]
Thanks kashif . Thankyou very much.

I am reviewing that doc. But one more query here , when we hit  fcm.send  method for fire notification then by inspecting response we got a key : success: true/false.  a query over ,  is this success key  is for reaching that notification to Firebase or of delivering message to device . Because sometimes  message not got delivered and i got true in this key . So please help by letting me know this.

Thanks

**Comment by kashif** [comment]
the response you get is the response sent back from the firebase service. So have a look here for the different types of responses:

https://firebase.google.com/docs/cloud-messaging/http-server-ref#table5
