### ISSUE TITLE
Message not posting for Firebase

### ISSUE THREAD

**Issue by vishalchinchane** [spacialdb/fcm#28]
I am getting the response as 
 {:body=>"{\"multicast_id\":6960682389725131834,\"success\":2,\"failure\":0,\"canonical_ids\":0,\"results\":[{\"message_id\":\"0:1497533189234401%0aef4f2ef9fd7ecd\"},{\"message_id\":\"0:1497533189249924%0aef4f2ef9fd7ecd\"}]}", :headers=>{"content-type"=>["application/json; charset=UTF-8"], "date"=>["Thu, 15 Jun 2017 13:26:29 GMT"], "expires"=>["Thu, 15 Jun 2017 13:26:29 GMT"], "cache-control"=>["private, max-age=0"], "x-content-type-options"=>["nosniff"], "x-frame-options"=>["SAMEORIGIN"], "x-xss-protection"=>["1; mode=block"], "server"=>["GSE"], "alt-svc"=>["quic=\":443\"; ma=2592000; v=\"38,37,36,35\""], "accept-ranges"=>["none"], "vary"=>["Accept-Encoding"], "connection"=>["close"]}, :status_code=>200, :response=>"success", :canonical_ids=>[], :not_registered_ids=>[]} 
But the message is not there on firebase console or not posted to device

**Comment by mquispe1185** [comment]
i have the same issue, were you able to solve this problem??

**Comment by vanitu** [comment]
I solved that when start using prodiction key. 
Not working with developer one.

**Comment by mquispe1185** [comment]
and where i get the production key and where should i change this option?? please answer me

**Comment by jpjofre94** [comment]
Having the same issue. How did you solve this?

**Comment by mquispe1185** [comment]
In my case i solved it testing in other device. At first i was trying on a Huawei and when the app was closed (NOT IN BACKGROUND) in my server show this response with success but the notification never reached the device. but when the app is in background the notification is delivered succesfully. So in conclusion try in other device, test with app in background and with app closed.
also i suggest to read the firebase guide because there is a difference between send "data" and notification. Try to test sending ONLY notification first. without data

**Comment by jpjofre94** [comment]
@mquispe1185  Thanks! That solved my problem, at least for notifications.

**Comment by sabman** [comment]
seems @mquispe1185 worked Thanks!
