### ISSUE TITLE
FCM.new questions

### ISSUE THREAD

**Issue by donhill** [spacialdb/fcm#46]
Is the FCM class thread safe or should I create a new one for each request? Is there a way to set global options?

**Comment by sabman** [comment]
Though I'm not an expert on ruby threadsafely **I don't think it's threadsafe at the class level**. If you create instances and don't try to modify anything at the class level it should be threadsafe. But if you try to modify the class you might end up inadvertently changing unrelated instance execution. 

We do have one dependency HTTParty which apparently dosen't take thread safety into account. https://github.com/jnunemaker/httparty/issues/511

Alse we could improve a few things for example we should call `freeze` on our constants (currently we don't) That's easy to fix though: https://github.com/spacialdb/fcm/blob/master/lib/fcm.rb#L12-L13 Otherwise it's a pretty simple gem we only two instance variables https://github.com/spacialdb/fcm/blob/master/lib/fcm.rb#L18-L19
 
The checklist of class safety smells: don't use/do the following:

- [x] Class variables (@@foo)
- [x] Class instance variables (@bar, trickier to find since they look the same as any old ivar)
- [x] Constants, ENV variables, and potential variables through which they can be mutated.
- [x] Memoization, especially when one of the two above points are involved
- [x] Creation of new threads (Thread.new, Thread.start). These obviously aren’t smells just by themselves. However, the risks mentioned above only materialize when shared across threads, so you should at least be familiar with in which cases the library is spawning new threads.

If there is a specific example you are thinking of?

**Comment by sabman** [comment]
@donhill if this answers your question please close this issue

**Comment by bar** [comment]
@sabman uhh? am I trickier?

**Comment by sabman** [comment]
Out of date. Please try with the new version. closing for now.
